#default
spring:
  jpa:
    open-in-view: false
    generate-ddl: false
  profiles:
    active: dev
server:
  tomcat:
    connection-timeout: 6000
    threads:
      max: 500
      min-spare: 40
    accept-count: 3
    max-connections: 300
    mbeanregistry:
      enabled: true
  port: 8740

---

spring:
  rabbitmq:
    host: # 호스트 주소
    port: # 호스트 포트번호
    username: # 유저네임
    password: # 유저 패스워드
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name:
    url:
    username:
    password: