#default
spring:
  rabbitmq:
    host:
    port:
    username:
    password:
  jpa:
    open-in-view: false
    generate-ddl: false
  profiles:
    group:
      "develop": "dev"
server:
  tomcat:
    connection-timeout: 6000
    threads:
      max: 500
      min-spare: 40
    accept-count: 3
    max-connections: 300
    mbeanregistry:
      enabled: true
  port: 8740

---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name:
    url:
    username:
    password: