#default
spring:
  rabbitmq:
    host: # 호스트 주소
    port: # 호스트 포트번호
    username: # 유저네임
    password: # 유저 패스워드
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  profiles:
    group:
      "develop": "dev"
server:
  tomcat:
    connection-timeout: 6000
    threads:
      max: 500
      min-spare: 40
    accept-count: 3
    max-connections: 300
    mbeanregistry:
      enabled: true
  port: 8740 # 어플리케이션 port

---

spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    driver-class-name: # 데이터베이스 드라이버 설정
    url: # 데이터베이스 접속 정보
    username: # 데이터베이스 접속 시 입력할 username 정보
    password: # 데이터베이스 접속 시 입력할 password 정보