#default
spring:
  profiles:
    group:
      "develop": "dev"
management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
server:
  tomcat:
    connection-timeout: 6000
    threads:
      max: 500
      min-spare: 40
    accept-count: 3
    max-connections: 300
    mbeanregistry:
      enabled: true
---

spring:
  config:
    activate:
      on-profile: "dev"
  rabbitmq:
    host: # 호스트 주소
    port: # 호스트 포트
    username: # 유저네임
    password: # 유저암호
fcm:
  auth: # fcm authkey 입력
  url: https://fcm.googleapis.com/fcm/send