global:
  scrape_interval:     10s
 
scrape_configs:
  - job_name: 'spring--app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'node'
    static_configs:
        - targets: ['host.docker.internal:9100']