#default
spring:
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  profiles:
    active: dev
management:
  metrics:
    distribution:
      percentiles:
        http: 0.95, 0.9, 0.7, 0.5, 0.3
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  server:
    port: 8081
server:
  tomcat:
    connection-timeout: 6000
    threads:
      max: 500
      min-spare: 40
    accept-count: 3
    max-connections: 300
    mbeanregistry:
      enabled: true

---

spring:
  config:
    activate:
      on-profile: dev
  rabbitmq:
    host:
    port:
    username:
    password:
  datasource:
    driver-class-name:
    url:
    username:
    password:
fcm:
  auth: auth
  url: https://fcm.googleapis.com/fcm/send