server:
  port: 8089
spring:
  rabbitmq:
    host: # 호스트 주소
    port: # 호스트 포트번호
    username: # 유저네임
    password: # 유저 패스워드
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test;DB_CLOSE_ON_EXIT=FALSE  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create