# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      accesskey: ${{  secrets.accesskey  }}
      secretkey: ${{  secrets.secretkey  }}
      GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

    permissions: read-all
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Remove gradle cache
      run: | 
       rm -rf /home/runner/.gradle/caches/
       rm -rf /home/runner/.gradle/wrapper/
      shell: bash
    - name: Run gradle
      run: |
        ./gradlew clean
        ./gradlew test
        ./gradlew build
      shell: bash
    - name: continuous deploy
      run: |
       pwd
       ls
       mkdir deploy
       cp build/libs/*.jar deploy/
       cd deploy && zip -r app.zip .
       cd ..
       sudo add-apt-repository ppa:deadsnakes/ppa
       sudo apt-get update -y
       sudo apt install python3.11 -y
       python --version
       cd script
       python deploy.py $accesskey $secretkey
      shell: bash
